/* This file is automatically generated and should not be edited directly. */

export type Version =
  | 'html-5'
  | 'html-4.01-strict'
  | 'html-4.01-transitional'
  | 'xhtml-1.1'
  | 'xhtml-1.0-strict'
  | 'xhtml-1.0-transitional'
  | 'recommended';

export const doctypes: Record<Version, string> = {
  'html-5': '<!DOCTYPE html>',
  'html-4.01-strict':
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">',
  'html-4.01-transitional':
    '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
  'xhtml-1.1':
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">',
  'xhtml-1.0-strict':
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">',
  'xhtml-1.0-transitional':
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',
  recommended:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',
};
